### ISSUE TITLE
Cannot find class FormulaTokenTypes

### ISSUE THREAD

**Issue by 0xae** [salesforce/formula-engine#60]
Hello there, Good days.
First of all thanks for open sourcing this great product, i am sure it's a great contribution towards open source and the common development of dynamic programming.

I did a little weekend hackathon and managed to compile the project and run formulas, but i had to do the dirty trick of 
```
mvn package -DskipTests
```
in order to build the jar artifacts.

The problem is that i am having problems compiling the impl project, because in the [FormulaUtils](https://github.com/salesforce/formula-engine/blob/1bf33c1fc25617df5fcf1c2e6190c19648218604/impl/src/main/java/com/force/formula/impl/FormulaUtils.java#L12) class it's importing the class
```java
import com.force.formula.parser.gen.FormulaTokenTypes;
```
but it cannot seem to find it.

I suspected maybe it's a generated class from antlr grammar but i attempted to run the command
```
mvn antlr:generate
```
but to no avail. I've run out of options and still trying to figure out whats happening, could you please help?

Thanks for the Attention.

**Comment by steventamm** [comment]
Which version of maven are you using?  The antlr2 parser generator (antler-maven-plugin on line 90 of impl/pom.xml) hasn't been touched in a decade, but it's needed for backwards compatibility.

**Comment by steventamm** [comment]
I think you'd need maven 3.8.  Jdk 8 should work.

**Comment by steventamm** [comment]
Maven runs the antlr 2 parser generator automatically. There's no need for an explicit command.

**Comment by steventamm** [comment]
I'm looking into JDK 17 support and Jdk8 won't work...

**Comment by 0xae** [comment]
Hi there, i found a way to run it under jdk8, not so sure about JDK 17.

**Comment by steventamm** [comment]
The grammaticus dependency is incompatible with jdk17, so I put a fix in that package. 

Antlr2's maven plug-in doesn't work with jdk17 either. There is a replacement, but I use M2Eclipse and it's not compatible directly.  

For JDK8, was there an easy workaround (besides changing the Pom to use 8)?

**Comment by 0xae** [comment]
After building the jar binary with maven, i Extract and merge the contents of these jars: formula-engine-api-0.2.8-SNAPSHOT.jar, formula-engine-impl-0.2.8-SNAPSHOT and grammaticus-1.1.0 into a single folder and insert into the com folder of the jar.

I am pretty sure that my pom.xml misses some critical build phase to do that job automatically, but for now this manual setup does the job.

Before i tried this, the application would fail on startup with an Unresolved Compilation of some sorts.

**Comment by steventamm** [comment]
To fix jdk17 and m2e, I may need to explicitly add the generated source folders for antlr in the pom. That should help with your issue.

**Comment by 0xae** [comment]
Yeah, that would be great!

Say how difficult it would to add some add features like bracket access [0], or nested json access like object.fields.name
I've tried to implement the dot notation resolution but still strugling.

**Comment by steventamm** [comment]
Bracket access is in DynamicReference.  It's not the best documentation but it should work.
JSONPATH and JSONPATHVALUE are optional, but aren't supported in all DBs.

JDK8 is going to be considered "unsupported", so I'll close this issue.
